### ISSUE TITLE
Upgrade Java SDK to use contracts 1.0 including NFTs

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/sdk-java#43] opened 2021-04-13 07:20 UTC
Changes to implement:
- [x] Migrate service agreements and conditions to contracts v1.0
- [x] Implement new NFTs templates and conditions

**Comment by r-marques** [comment] 2021-05-25 07:27
@aaitor maybe we can close this one since it's a duplicate of #45. Or #45 doesn't include the NFTs?

**Closed** 2021-06-22 13:22 UTC
